@startyaml
  -
      nom: LEON
      cache:
          - Un cache d'instructions & un data cache (type direct-mapped)
          - Désactivation du cache après une interruption
          - PIRE TEMPS D'EXECUTION = TEMPS NORMAL D'EXECUTION + TEMPS D'INTERRUPTION
      Mémoire:
          - Interface flexible permettant d'ajouter des mémoires de type DRAM ou SRAM
          - 32 Bits avec un code 7-bit SEC/DED BCH pour la détection d'erreurs et leurs corrections
      I/O_Interface:
        - Interface PCI (type synchrone multi/master)
        - Debit de transfert de 132 Mbyte/s en mode 32-bit & 528 Mbyte/s avec 64-bit
      composants:
        - 1
        - 2
  -
      nom: LEON 2
      cache:
          - Désactivation du cache après une interruption
          - PIRE TEMPS D'EXECUTION = TEMPS NORMAL D'EXECUTION + TEMPS D'INTERRUPTION
      Mémoire:
          - Interface flexible permettant d'ajouter des mémoires de type DRAM ou SRAM
          - 32 Bits avec un code 7-bit SEC/DED BCH pour la détection d'erreurs et leurs corrections
      I/O_Interface:
          - Interface PCI (type synchrone multi/master)
          - Debit de transfert de 132 Mbyte/s en mode 32-bit & 528 Mbyte/s avec 64-bit
      Floating_Point_unit:
          - Pipeline 5-stage
          - Nouveau système basé sur le Meiko floating-point core
      Signaux:
          - Tous les signaux sont au front montant de CLK
          - 29 signaux différents
      composants:
          - 1
          - 2
  -
      nom: LEON 3 / GRLIB IP
      raison: LEON 2 était censé etre utilisé sur un processeur mais était de plus en plus utilisé sur les SOC. D'où la nécessité de LEON 3
      cache:
          - Désactivation du cache après une interruption
          - PIRE TEMPS D'EXECUTION = TEMPS NORMAL D'EXECUTION + TEMPS D'INTERRUPTION
      Mémoire:
          - MMU
          - Interface flexible permettant d'ajouter des mémoires de type DRAM ou SRAM
          - 32 Bits avec un code 7-bit SEC/DED BCH pour la détection d'erreurs et leurs corrections
      I/O_Interface:
        - Interface PCI (type synchrone multi/master)
        - Debit de transfert de 132 Mbyte/s en mode 32-bit & 528 Mbyte/s avec 64-bit
      Floating_Point_unit:
          - Pipeline 7-stage
          - Nouveau système basé sur le Meiko floating-point core
      Signaux:
          - Tous les signaux sont au front montant de CLK
          - 29 signaux différents
      Bus:
          - interface de bus AMBA 2
      composants:
          - 1
          - 2
  -
      nom: LEON 4 / GRLIB IP
      cache:
          - Désactivation du cache après une interruption
          - PIRE TEMPS D'EXECUTION = TEMPS NORMAL D'EXECUTION + TEMPS D'INTERRUPTION
      Mémoire:
          - Interface flexible permettant d'ajouter des mémoires de type DRAM ou SRAM
          - 32 Bits avec un code 7-bit SEC/DED BCH pour la détection d'erreurs et leurs corrections
      I/O_Interface:
          - Interface PCI (type synchrone multi/master)
          - Debit de transfert de 132 Mbyte/s en mode 32-bit & 528 Mbyte/s avec 64-bit
      Floating_Point_unit:
          - Norme compatible avec les normes EE-754/IEEE-1754 
          - Pipeline 7-stage
          - Nouveau système basé sur le Meiko floating-point core
      Signaux:
          - Tous les signaux sont au front montant de CLK
          - 29 signaux différents
      Autres:
          - Une unité de prédiction
          - Un bus de processeur 64 ou 128 bits
          - Cache de Niveau 2
      composants:
          - 1
          - 2
  -
      nom: LEON 5 / GRLIB IP
      raison:  LEON5 vjse les hautes architectures FPGA et la technologie ASIC deep-submicron
      cache:
          - Caches de type I/D multi-set de niveaux 1
          - Un cache optionnel de niveau 2
      Mémoire:
          - MMU
      I/O_Interface:
        - Interface PCI (type synchrone multi/master)
        - Debit de transfert de 132 Mbyte/s en mode 32-bit & 528 Mbyte/s avec 64-bit
      Floating_Point_unit:
        - Norme IEEE-754
          - Pipeline 7-stage
          - Nouveau système basé sur le Meiko floating-point core
      Signaux:
          - Tous les signaux sont au front montant de CLK
          - 29 signaux différents
      Autres:
          - Une unité de prédiction
          - Un bus de processeur 64 ou 128 bits
          - Cache de Niveau 2
      composants:
          - 1
          - 2
@endyaml